// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gnglbyoevqzlggjfgrwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduZ2xieW9ldnF6bGdnamZncndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTE5ODUsImV4cCI6MjA3NDQ4Nzk4NX0.4PDKyl-xK-VjnNpw-E0fFoA1V-fSVpHkz66_L1HwaIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);